### PR TITLE
 Dhafer and Saad Task

### PR DESCRIPTION
**Pull request by ssalharbi**
# Description
adding a bar chart the shows the graded task in progress dashboard

## Type of change
Adding Chart
Please delete options that are not relevant.

- [a bar chart shows tasks that are graded ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
it works and the chart are shown in the progress dashboard

# Checklist:

- [yes ] My code follows the style guidelines of this project
- [ yes] I have performed a self-review of my own code
- [ yes] I have commented my code, particularly in hard-to-understand areas
- [ not yet] I have made corresponding changes to the documentation
- [ yes] My changes generate no new warnings
- [yes] I have added tests that prove my fix is effective or that my feature works
- [yes ] New and existing unit tests pass locally with my changes
- [yes ] Any dependent changes have been merged and published in downstream modules

If you have any questions, please contact @macite or @jakerenzella.

Thanks
Dhafer ALshehri
Saad Alharbi

### CODE REVIEW

**Comment by jakerenzella** [comment]
Can the pull request show a screenshot of the bar chart? Cheers

**Comment by ssalharbi** [comment]
ok sure , attached
Screenshot from 2020-05-16 23-25-30

**Comment by ssalharbi** [comment]
we will try to show it in the request 
thanks

**Comment by macite** [comment]
Quality Points and grades are different things - you will need to adjust this to use task grades not quality points.

**Comment by ssalharbi** [comment]
Hi Andrew
Thank you for your feedback.
At this time of your comments we have submitted the handover documents for this trimester. However, sure your feedback will be considered. We will document it and continue working on it in the next trimester.
Thanks.

**Pull request closed without merging**
