### PR TITLE
Doubtfire-web Installation Updates

### PR DESCRIPTION
**Pull request by Justfeedme**
This PR seeks to merge updates to the Doubtfire-web installation in Ubuntu. Specifically, it creates an installation script, and updates the corresponding information in the readme.md.

# How Has This Been Tested?

The installation process described in the updated documentation has been tested from scratch, resulting in a functional instance of Doubtfire-web. Similarly, the ./setup.sh script has been tested from scratch (n.b. only using Ubuntu 18.04 LTS), also resulting in a functional instance of Doubtfire-web.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

If you have any questions, please contact @macite or @jakerenzella.

### CODE REVIEW

**Comment by jakerenzella** [comment]
Will review tomorrow 👍

**Comment by Justfeedme** [comment]
In line with @macite's recommendations, updated commit messages for formatting consistency.

**Comment by macite** [comment]
Can you expand out the setup script to run all parts of the setup on Mac or Linux?

**Comment by Justfeedme** [comment]
@macite Yes, although that will likely have to be a future body of work to be completed in conjunction with updating the Mac installation documentation.

**Pull request merged**
