### PR TITLE
Enhance/expanding comment box

### PR DESCRIPTION
**Pull request by jakerenzella**

### CODE REVIEW

**Comment by alexcu** [comment]
@jakerenzella Make sure you have overcommit installed to prevent commit messages from being truncated if they're too long 😊 

Do you have any images of how it's visually changed? Could you put them in the description?

**Comment by jakerenzella** [comment]
Sure how do you want me to fix this stuff up then?

**Comment by alexcu** [comment]
Don’t worry about it for now 😊

**Comment by jakerenzella** [comment]
screen shot 2016-04-05 at 4 43 18 pm

Here you can see that the comment box will expand based on line lengths, the send button is now fixed to the top right :)

Also Preview pane has it's disabled scrollbars removed.

**Pull request merged**
