### PR TITLE
Migrate/privacy policy

### PR DESCRIPTION
**Pull request by Chanputhi**
_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [x] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from @macite and @jakerenzella on the Pull Request

### CODE REVIEW

**Comment by Chanputhi** [comment]
This services component of the 'privacy policy' is completed and tested on Google Chrome. There is no error and the result is shown.

**Review by lst97 — CHANGES_REQUESTED** [review]
@Chanputhi  Please revert this change https://github.com/doubtfire-lms/doubtfire-web/pull/663/commits/a0a6ec3b4fd9a0a4f85fd3489fa1918008634029 , because you should not remove the alert-list in the privacy-policy branch. Each branch should just focus on the dedicate work. Thank you.

**Comment by Chanputhi** [comment]
This component is no longer used because I developed it in the previous version before the new version was released.
However, I have implemented it on the new version already.
Here is the link to the new version which needs approval. 
https://github.com/doubtfire-lms/doubtfire-web/pull/664

**Comment by lst97** [comment]
Convert this request to draft or close it if duplicated.

**Pull request closed without merging**
