### PR TITLE
Enhance/add emoji

### PR DESCRIPTION
**Pull request by jakerenzella**
# Description

This PR adds an emoji-picker component, supporting both graphical selection and in-text selection similar to Slack.
emoji

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Thorough front-end testing.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by macite** [comment]
Does this inject the emoji character into the comment or retain the markup which is replaced when it is rendered? I don't think the database currently supports emoji characters in production - but it does work in dev...

**Comment by jakerenzella** [comment]
Damn, no it's directly injecting the emoji into the comment text as a string. Is it possible to migrate the database to support it?

**Comment by macite** [comment]
We could look at that, but then also need to look at how this works when we create PDFs etc.

Could we have the comment text and rendered text as different? So replace all :...: with the emoji in the render but keep it for the comment itself?

**Comment by jakerenzella** [comment]
Yes this approach should work, I'll spend some time on it and see.

**Comment by jakerenzella** [comment]
@macite the comment string now only stores the colon patterns, the frontend just renders the strings as emojis now 👍

**Comment by jakerenzella** [comment]
Just tested the generated portfolio PDF and all working, in there you will see the `:+1:`

**Pull request merged**
