### PR TITLE
New create unit component

### PR DESCRIPTION
**Pull request by GaganSinghGit**
# Description

As part of component migration. The component here is create unit modal. There are 2 new field added start date and end date.
Changes made:
1. Created new component create-new-unit-modal.component.ts to replace the older AngularJS component
2. Added 2 new date fields (start and end date) in the modal
3. Downgraded the component in doubtfire-angularjs.module.ts because the parent component of the modal is still AngularJS component.Fixes # (issue)
4. Imported material ui (MatDatepickerModule, MatNativeDateModule, MatDialogModule as MatDialogModuleNew) modules which are used in the component.

Before:
Screen Shot 2023-05-10 at 10 01 14 pm
After:
Screen Shot 2023-05-10 at 10 01 25 pm

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I tested it by creating new units.

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from @macite and @jakerenzella on the Pull Request

### CODE REVIEW

**Comment by maddernd** [comment]
This pull request needs to go to thoth tech doubtfire web.

**Comment by GaganSinghGit** [comment]
Hi,
Andrew told me create the pull request on this, not the thoth tech one.

**Comment by jakerenzella** [comment]
Is there a relation to https://github.com/doubtfire-lms/doubtfire-web/pull/701?  Which should be reviewed/closed

**Comment by jakerenzella** [comment]
dupe

**Pull request closed without merging**
