### PR TITLE
Split api file into subfiles

### PR DESCRIPTION
**Pull request by jakerenzella**
* Move api-url into its own file
* Move resource-plus to its own file
* Add models directory
* Move Project to be its own file
* Move Unit to be its own file
* Move unit-role to be its own file
* Move user role to its own file
* Move convenor to its own file
* Move tutor to its own file
* Move tutorial to its own file
* Move learning alignments to its own file
* Move intended-learning-outcome into its own file
* Move task into its own file
* Move task-comment to its own file
* Move task-definition to its own file
* Move group-member to its own file
* Move group to be its own file
* Move group-set to be its own file
* Move task-alignment to be its own file
* Move task-feedback to its own file
* Move task-similarity to its own file
* Move students to its own file
* Move user to its own file
* Move task-completion-CSV to its own file
* Move portfolio-submission to its own file

### CODE REVIEW

**Comment by macite** [comment]
This breaks for me -- it seems to be branched from prior to the switch to lodash!
@alexcu and @jakerenzella can you look into this...

**Comment by alexcu** [comment]
@macite There seems to be something wrong—the whole branch has been broken 😞 And I've begun the entire restructure with `findWhere` and other old lodash methods present 😞

Damn it.

**Comment by alexcu** [comment]
@macite Is it possible that we don't have your lodash commit in `develop` for some reason?

**Comment by macite** [comment]
@alexcu I can see `NEW: add additional analytics reporting events. Change to lodash 4.2.0` and develop does use correct lodash code.

I suggest that you and @jakerenzella run `bower prune` to make sure the old lodash version is gone.

**Comment by alexcu** [comment]
This is awful. The `quality/structure-refactor` doesn't have this :(

**Comment by macite** [comment]
Any ideas how this happened?

**Comment by alexcu** [comment]
No ideas. I've looked into it and we branch `quality/common-refactor` and `quality/api-refactor` off `quality/structure-refactor`. However, while `quality/structure-refactor` is OK (ignore previous comment—have confirmed that branch is ok) the other branches are not.

I have no idea how it happened... very bizarre. I may try rebasing and see if I can fix it... here goes nothing

**Comment by alexcu** [comment]
I don't know what it's doing. If I rebase against develop everything is fine. But as soon as I add those changes they are there again.

**Comment by macite** [comment]
Wait... for me `quality/structure-refactor` is also missing the lodash commits. Its last commit was 1st Feb!

**Comment by alexcu** [comment]
😞 how? Let me try rebasing again

**Comment by alexcu** [comment]
I've managed to rebase and it's ok now, I will try pushing. I can help @jakerenzella fix this tomorrow—very complicated.

**Comment by macite** [comment]
Have you pushed this to `quality/structure-refactor`?

**Comment by alexcu** [comment]
Here we go, there are now merge conflicts. This is because `quality/structure-refactor` was out of date. I don't know how this happened, probably forgot to pull somewhere along the way. But at least we can now resolve these conflicts as per above.

**Comment by macite** [comment]
Looks like the conflicts wont help much -- its just indicating that everything in API is gone... We need to make sure that the moved code has any changes that occurred in api... though its most likely just layout changes. -- so be careful here.

**Comment by jakerenzella** [comment]
I could just re-split the api file?

**Comment by macite** [comment]
I think that will be what is needed :disappointed: -- the files are already there so you should be able to copy the "new" api code across. Most likely there are only few changes.

**Comment by jakerenzella** [comment]
Not a problem :)

**Comment by alexcu** [comment]
May have figured out what is needed without @jakerenzella redoing it... fingers crossed all goes well tomorrow morning when we meet to figure this one out

**Comment by alexcu** [comment]
Got a fix for this.

Basically, `quality/structure-refactor` wasn’t updated against `develop`. Ran the following

```
git checkout quality/structure-refactor
git pull upstream develop                       # get the latest changes from doubtfire-lms/doubtfire-web/develop
git rebase upstream/develop                     # rebase those changes in my branch (quality/structure-refactor)
git push origin quality/structure-refactor -f   # push my changes to github
```

then re-run against `quality/structure-refactor` instead of `develop` for all other `quality/X-refactor` branches (worked for my other branches on doubtfire-lms/

**Comment by jakerenzella** [comment]
Consolidated all merge issues with upstream.

**Comment by alexcu** [comment]
Great! Now we can also merge in `quality/common-refactor` and `quality/error-refactor` too :)

**Pull request merged**
