### PR TITLE
Add grade task visualization

### PR DESCRIPTION
**Pull request by ssalharbi**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Add graded visualization

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

If you have any questions, please contact @macite or @jakerenzella.
grad-vis

### CODE REVIEW

**Comment by jakerenzella** [comment]
Can you include a screenshot of the new visualisation?

**Comment by jakerenzella** [comment]
I also can't accept "Dhafer and Saad Task" as a commit message, commit messages need to describe small changes in the commit.

**Comment by ssalharbi** [comment]
Hi Jack. The commit is from previous iteration, and we understand it's not informative.  Even if we re-do the pull, it will still appear. In addition, for next iteration, we will try to migrate the visualization component. Regards.

**Comment by macite** [comment]
Who is Jack?

Can you send through a design first? Also all new UI changes need to be in Angular not the old AngularJS code.

When submitting a PR it needs to be descriptive, not just the template text.

Closing this.

**Pull request closed without merging**
