### PR TITLE
Nishant and Muhammad

### PR DESCRIPTION
**Pull request by nysh97**
Description-

Show the strength of the alignment - the current 5 circles are not good :(

The task alignment visualisation on the Intended Learning Outcomes page does not really help communicate what is intended. Each of the circles has an associated meeting and potentially could be better communicated.

Fixes -
Frontend fixes have been done to make it better communicable:
1. Html file has been updated with gylyphicon class
2. A loop has been used to show colors with increasing density with all the colors defined at the beginning, all this has been done on sass file.

 How Has This Been Tested?

Whole project has been run and tested and no additional functionality's are causing any issues.

 Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jakerenzella** [comment]
Can we get a screen shot of the changes in this PR?

**Comment by nysh97** [comment]
image

**Comment by jakerenzella** [comment]
This can't be accepted, and should never have been proposed.

* How does changing the circle to a star improve this feature?
* The unselected stars are smaller and don't appear inline with the selected stars in your own screenshot.
* The contrast with the bright yellow and the white background is not great enough, what about users with vision issues?

**Comment by nysh97** [comment]
Hey Jake,
Sorry if the pull request doesn’t justifies on what needs to be done.
I have sent proposal multiple times, had nothing update from your side. Can
I have some feedback with nee proposal which I’ll send you in the coming
week, so without wasting much time I’ll get back on working on it

**Comment by macite** [comment]
Where is your proposal? I provided feedback on your background document but I haven't receive any new designs since... There does not appear to have been a redesign here - circles to stars.. really how is that a redesign?

**Pull request closed without merging**
