### PR TITLE
Enhance/add task inbox sorting

### PR DESCRIPTION
**Pull request by jakerenzella**
# Description

This PR adds the ability for tutors to sort the task inbox by the task definition. It uses the task definition sequence number as the key to sort. 

Notes:

* Why not use a sortPipe? : These are not necessarily recommended by the Angular team, and we have some custom logic we need to execute to store the original order of the task list.

* Potential memory concern: We need to store the original task list in order so that we can revert back to the default order, which means for large task lists we may be doing a fair bit of copying. I can't see a nice way around this other than more significant changes to add some details to each element in the task list to store some ordering information. 

Addresses #367 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Testing Checklist:

- [X] Tested in latest Chrome
- [X] Tested in latest Safari
- [X] Tested in latest Firefox

Screen Shot 2021-06-18 at 12 59 38 pm
Screen Shot 2021-06-18 at 12 59 30 pm

### CODE REVIEW

**Comment by macite** [comment]
We could use a sort pipe - and use pipe for filters... is it worth changing?

Even a large task list would be a very small data structure -- we are not copying the tasks themselves, just references to them. Though we do need to address the large task list issue anyway :)

**Comment by jakerenzella** [comment]
@macite We can't use a sortPipe in this instance until we make the underlying improvements to the task inbox on the backend as we need to hook into the component's lifecycle to determine when to copy the list. Maybe it's possible with the pipe but I think it would be more complicated than its worth

Yes I think you're right, the issues with the task list at the moment is with rendering, not with the actual data structure... In this case I think we both agree this is good to merge :) Thanks

**Comment by jakerenzella** [comment]
@macite Oh and please confirm that the `seq` key is the best item to sort on here, there's a few options like the name of the task or the abbreviation, but I think this is the best approach (however I'm not actually sure what seq is, I think it's just the order of the task in the task list, so does that mean if a unit creates a new week 5 task in week 9, it would then be appear later in the sequence?)

**Comment by macite** [comment]
Yes - seq is good :)

**Pull request merged**
