### PR TITLE
refactor(migration): replace-fx-layout-with-tailwind-equivalent-user-badge

### PR DESCRIPTION
**Pull request by syedfaiq**
Replaced fx-layout with equivalent tailwind maintaining the quality of the user-badge

### CODE REVIEW

**Comment by syedfaiq** [comment]
Before:
image

After:
image

**Comment by maddernd** [comment]
@jakerenzella please can you do the final review on this.

**Comment by jakerenzella** [comment]
Similarly here the spacing is different, this is a regression.

**Comment by SaimSaudagar** [comment]
image

**Pull request closed without merging**
