### PR TITLE
Migrate/file uploader

### PR DESCRIPTION
**Pull request by Anusreekizhakkekappil**
*Any italic text should be deleted from the final Pull Request text, including this line*

# Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes # (issue)

## Type of change

*Please delete options that are not relevant.*

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

## Testing Checklist:

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from @macite and @jakerenzella on the Pull Request

### CODE REVIEW

**Comment by Anukappil** [comment]
Migration of file uploader- creating replacement files

**Comment by erickao5858** [comment]
The name of this pull request is inappropriate, please use other pull requests as an example.

**Review by erickao5858 — COMMENTED** [review]
The code seems good in this stage.

**Comment by macite** [comment]
File uploader needs to be migrated to angular and material, and the process should be refactored.

**Pull request closed without merging**
