### PR TITLE
refactor(migration): replace-fx-layout-with-tailwind-equivalent-hero-sidebar

### PR DESCRIPTION
**Pull request by syedfaiq**
Replaced fx-layout with equivalent tailwind maintaining the quality of the hero side-bar

### CODE REVIEW

**Comment by syedfaiq** [comment]
Before:
image

After:
image

**Comment by maddernd** [comment]
@jakerenzella please can you do the final review on this.

**Comment by jakerenzella** [comment]
From the screenshot alone this doesn't look right 👍

**Comment by syedfaiq** [comment]
After 2nd commit of sigin-up page:
image

**Comment by maddernd** [comment]
We still need to see the entire screenshot showing that everything matches please.

**Comment by SaimSaudagar** [comment]
image


You'll have to pull both sign in and hero sidebar pages to see the exact changes as they are on the same page.

**Comment by maddernd** [comment]
@jakerenzella can you please review this one

**Comment by syedfaiq** [comment]
image

You'll have to pull sign in page and hero sidebar together to get the exact changes as they are on the same page.

**Pull request closed without merging**
